Artifact Necklace Heirloom: Deeja-Wujeeta
Umbra-Cosmatic-Drift/Umbra-CD pull request #43
Opened 2024-03-22 16:37 UTC by Gotimanga

## About the PR
Adds a new Heirloom for the character: Deeja-Wujeeta on the Umbra codebase. If this somehow uploads to the wrong repo I will cry.

## Why / Balance
Cool thing to own. This is a purely cosmetic heirloom. It has a custom artifact nodegraph with only one node - a node that on inspect will make everyone around it feel positive.

## Media

https://github.com/Umbra-Cosmatic-Drift/Umbra-CD/assets/127038462/7aa5c090-e1f0-45c3-a6c6-8c0f7c32ab75

Hopefully not too dark. I will change the video to a higher quality one if required.
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
Not required

2024-03-22 16:47 UTC, TsjipTsjip requested changes

2024-03-22 16:47 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Clothing/Neck/arti-necklace.yml
File should include a comment at the top of the entity block:
```yml
# Player: Deeja - Character: Deeja-Wujeeta
```

2024-03-22 18:38 UTC, Aexxie requested changes
You should rename the YAML file to `misc.yml`, and rename it internally to `ArtifactNecklace`. This includes file names, you should avoid using hyphens.

TL;DR
- Rename `arti-necklace.yml` to `misc.yml`
- Change the ID to be `ClothingNeckArtifactNecklace`
- Change the RSI to `artifactnecklace.rsi`

2024-03-22 21:10 UTC, Gotimanga commented
@Aexxie I believe that's all the changes requested. I don't think I've missed anything

2024-03-22 21:11 UTC, Gotimanga commented
Except for the fact I typed Misc with a K. Oops

2024-03-22 21:14 UTC, Aexxie approved these changes

2024-03-22 22:29 UTC, TsjipTsjip approved these changes
GM approval.

2024-03-24 09:20 UTC, merged

2024-03-24 09:22 UTC, Gotimanga commented
:D

2024-03-24 09:23 UTC, Kukutis96513 commented
ooh nice